"""booking contact fields

Revision ID: 246f458bf59a
Revises: e6fbb7b4d82b
Create Date: 2026-09-29 10:49:22.817261

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "246f458bf59a"
down_revision: str | Sequence[str] | None = "e6fbb7b4d82b"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("bookings", sa.Column("contact_email", sa.String(length=320), nullable=True))
    op.add_column("bookings", sa.Column("contact_phone", sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("bookings", "contact_phone")
    op.drop_column("bookings", "contact_email")
    # ### end Alembic commands ###
